
[package]
# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = []

# The title and description fields are primarly for displaying extension info in UI
title = "Omniverse Graph Extension Example"
description="Example extension for OmniGraph nodes."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository="https://gitlab-master.nvidia.com/omniverse/kit-extensions/example"

# One of categories for UI.
category = "Example"

# Keywords for the extension
keywords = ["kit", "omnigraph"]

# Watch the .ogn files for hot reloading (only works for Python files)
[fswatcher.patterns]
include = ["*.ogn", "*.py"]
exclude = ["Ogn*Database.py"]

[dependencies]
"omni.kit.test" = {}
"omni.graph" = {}

# Main python module this extension provides, it will be publicly available as "import ur5sim.ros2contactpublisher".
[[python.module]]
name = "ur5sim.ros2contactpublisher"

# Additional python module with tests, to make them discoverable by test system.
[[python.module]]
name = "ur5sim.ros2contactpublisher.ogn.tests"
